# This is a basic workflow to help you get started with Actions

name: Java CI with Maven and S3 Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      # - develop
  pull_request:
    branches:
      - main
      # - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Get artifact name
        id: get_artifact_name
        run: echo "ARTIFACT_NAME=$(ls target/*.jar | xargs basename)" >> $GITHUB_ENV
        
      - name: Check if artifact exists
        run: ls -l target/$ARTIFACT_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload JAR to S3
        run: |
          aws s3 cp target/$ARTIFACT_NAME s3://us-east-1-iac-test-bucket/jars/$ARTIFACT_NAME
